Repository YKZSolutions/MMDC-Student-Portal, pull requests merged in 2025-09, with the labels that each got.

#88 [CAP-17] FEAT (FE): Revamp Authentication Pages (Login + Forgot Password)
  frontend/src/components/grid-background.tsx
  frontend/src/pages/shared/auth/login-page.tsx
  frontend/src/pages/shared/auth/reset-password-page.tsx
Labels: enhancement

#95 [CAP-137] CONF: Improve PR Type Checking Workflow
  .github/workflows/pr-type-check-dev.yml
  .github/workflows/pr-type-check-prod.yml
  backend/src/main.ts
Labels: enhancement

#100 [CAP-130] REFACTOR: (FE) improve and polished responsiveness across billing, users, and enrollment pages
  frontend/src/pages/admin/billing/create.tsx
  frontend/src/pages/admin/enrollment/$periodId.tsx
  frontend/src/pages/admin/enrollment/index.tsx
  frontend/src/pages/admin/users/users.admin.tsx
  frontend/src/pages/shared/billing/$billingId.tsx
  frontend/src/pages/shared/billing/index.tsx
  frontend/src/pages/shared/billing/redirect.tsx
  frontend/src/pages/shared/layout/topbar.tsx
  frontend/src/pages/student/enrollment/index.tsx
Labels: enhancement

#108 [CAP-184] hotfix: [FE] Renaming of courseEnrollment to courseEnrollments broke the frontend
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
  frontend/src/pages/student/enrollment/index.tsx
Labels: fix / hotfix

#116 [CAP-187] REFACTOR: (FE) Polish Grades Page
  frontend/src/features/courses/grades/grades-table.tsx
  frontend/src/pages/shared/courses/$courseCode/grades/index.tsx
Labels: enhancement

#122 [CAP-155 & 156] REFACTOR: (FE) Polish CMS and Courses Page #121
  frontend/src/components/multi-filter.tsx
  frontend/src/features/courses/cms/cms.tsx
  frontend/src/features/courses/cms/content-tree.tsx
  frontend/src/features/courses/cms/course-selector.tsx
  frontend/src/features/courses/dashboard/course-dashboard-filters.tsx
  frontend/src/features/courses/dashboard/course-dashboard-header.tsx
  frontend/src/features/courses/dashboard/course-dashboard-item.tsx
  frontend/src/features/courses/hooks/useEditorState.ts
  frontend/src/features/courses/hooks/useEditorState.tsx
  frontend/src/features/courses/modules/module-panel.tsx
  frontend/src/features/navigation/navLinks.tsx
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/@tanstack/react-query.gen.ts
  frontend/src/integrations/api/client/sdk.gen.ts
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
  frontend/src/pages/admin/courses/$courseCode/modules/index.tsx
  frontend/src/pages/admin/courses/index.tsx
  frontend/src/pages/shared/courses/$courseCode/assignments/index.tsx
  frontend/src/pages/shared/courses/$courseCode/grades/index.tsx
  frontend/src/pages/student/courses/$courseCode/modules/index.tsx
  frontend/src/pages/student/courses/index.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/(protected)/cms/$courseCode/index.tsx
  frontend/src/routes/(protected)/cms/index.tsx
  frontend/src/routes/(protected)/courses/$courseCode/modules/$itemId/create.tsx
  frontend/src/routes/(protected)/courses/$courseCode/modules/edit.tsx
  frontend/src/routes/(protected)/courses/index.tsx
  frontend/src/utils/helpers.ts
Labels: enhancement

#128 [CAP-191] Fix: (BE) MajorService logs error
  backend/src/modules/major/major.service.ts
Labels: fix / hotfix

#129 [CAP-198] FEAT: (FE) Toggling to Another Term for Courses Page for Admin Only
  frontend/src/features/courses/async-term-combobox.tsx
  frontend/src/features/courses/dashboard/course-dashboard-header.tsx
  frontend/src/pages/admin/courses/index.tsx
Labels: enhancement

#133 [CAP-209] CONF: (FE) Change the baseUrl based on .env
  frontend/src/routes/__root.tsx
Labels: enhancement

#139 [CAP-222] FEAT: (BE) Implement Structured Submission Workflow & Validation
  backend/prisma/schema.prisma
  backend/prisma/seed/constants/mockQuizQuestions.ts
  backend/src/generated/nestjs-dto/assignment.dto.ts
  backend/src/generated/nestjs-dto/assignment.entity.ts
  backend/src/generated/nestjs-dto/assignmentGradeRecord.entity.ts
  backend/src/generated/nestjs-dto/assignmentSubmission.dto.ts
  backend/src/generated/nestjs-dto/assignmentSubmission.entity.ts
  backend/src/generated/nestjs-dto/connect-assignmentGradeRecord.dto.ts
  backend/src/generated/nestjs-dto/connect-assignmentSubmission.dto.ts
  backend/src/generated/nestjs-dto/connect-moduleSection.dto.ts
  backend/src/generated/nestjs-dto/create-assignment.dto.ts
  backend/src/generated/nestjs-dto/create-assignmentGrading.dto.ts
  backend/src/generated/nestjs-dto/create-assignmentSubmission.dto.ts
  backend/src/generated/nestjs-dto/create-discussion.dto.ts
  backend/src/generated/nestjs-dto/create-moduleSection.dto.ts
  backend/src/generated/nestjs-dto/create-quiz.dto.ts
  backend/src/generated/nestjs-dto/create-quizSubmission.dto.ts
  backend/src/generated/nestjs-dto/create-sectionModule.dto.ts
  backend/src/generated/nestjs-dto/discussion.dto.ts
  backend/src/generated/nestjs-dto/discussion.entity.ts
  backend/src/generated/nestjs-dto/groupMember.entity.ts
  backend/src/generated/nestjs-dto/quiz.dto.ts
  backend/src/generated/nestjs-dto/quiz.entity.ts
  backend/src/generated/nestjs-dto/quizSubmission.dto.ts
  backend/src/generated/nestjs-dto/quizSubmission.entity.ts
  backend/src/generated/nestjs-dto/update-assignment.dto.ts
  backend/src/generated/nestjs-dto/update-assignmentGrading.dto.ts
  backend/src/generated/nestjs-dto/update-assignmentSubmission.dto.ts
  backend/src/generated/nestjs-dto/update-discussion.dto.ts
  backend/src/generated/nestjs-dto/update-moduleSection.dto.ts
  backend/src/generated/nestjs-dto/update-quiz.dto.ts
  backend/src/generated/nestjs-dto/update-quizSubmission.dto.ts
  backend/src/generated/nestjs-dto/update-sectionModule.dto.ts
  backend/src/modules/chatbot/chatbot.service.ts
  backend/src/modules/lms/content/assignment/assignment-submission.controller.ts
  backend/src/modules/lms/content/assignment/assignment-submission.service.ts
  backend/src/modules/lms/content/assignment/assignment.controller.ts
  backend/src/modules/lms/content/assignment/assignment.module.ts
  backend/src/modules/lms/content/quiz/dto/quiz-answers.dto.ts
  backend/src/modules/lms/content/quiz/dto/quiz-questions.dto.ts
  backend/src/modules/lms/content/quiz/quiz-submission.controller.ts
  backend/src/modules/lms/content/quiz/quiz-submission.service.ts
  backend/src/modules/lms/dto/submit-assignment.dto.ts
  backend/src/modules/lms/group/dto/detailed-group.dto.ts
  backend/src/modules/lms/group/group.service.ts
  backend/src/modules/lms/lms.controller.ts
  backend/src/modules/lms/lms.service.ts
  backend/src/modules/program/program.controller.ts
  backend/src/modules/submission/submission.controller.ts
  backend/src/modules/submission/submission.module.ts
  backend/src/modules/submission/submission.service.ts
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/@tanstack/react-query.gen.ts
  frontend/src/integrations/api/client/sdk.gen.ts
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
Labels: enhancement, fix / hotfix

#144 [CAP-211] FEAT: (FE) Create ModuleContent for a ModuleSection
  backend/src/modules/lms/dto/create-content.dto.ts
  backend/src/modules/lms/dto/detailed-module-section.dto.ts
  backend/src/modules/lms/lms-content.controller.ts
  backend/src/modules/lms/lms-content.service.ts
  backend/src/modules/lms/lms-section.controller.ts
  backend/src/modules/lms/lms-section.service.ts
  frontend/src/components/rich-text-editor.tsx
  frontend/src/components/submit-button.tsx
  frontend/src/features/courses/cms/cms.tsx
  frontend/src/features/courses/cms/content-details-editor.tsx
  frontend/src/features/courses/hooks/useCourseData.ts
  frontend/src/features/courses/hooks/useEditorState.tsx
  frontend/src/features/courses/mocks.ts
  frontend/src/features/courses/modules/content/module-content-view.tsx
  frontend/src/features/courses/modules/module-panel.tsx
  frontend/src/features/courses/modules/module-review-step.tsx
  frontend/src/features/courses/modules/types.ts
  frontend/src/features/courses/suspense.tsx
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/@tanstack/react-query.gen.ts
  frontend/src/integrations/api/client/sdk.gen.ts
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
  frontend/src/pages/admin/lms/$lmsCode/modules/index.tsx
  frontend/src/utils/helpers.ts
  frontend/src/utils/helpers.tsx
Labels: enhancement, fix / hotfix

#146 [CAP-212] FEAT/FIX/REFACTOR: (FE & BE) Fetch ModuleContent for a ModuleSection
  backend/src/modules/lms/lms-content.controller.ts
  backend/src/modules/lms/lms-content.service.ts
  frontend/src/components/rich-text-editor.tsx
  frontend/src/features/courses/cms/cms.tsx
  frontend/src/features/courses/hooks/useEditorState.tsx
  frontend/src/features/courses/modules/admin/add-module-drawer.tsx
  frontend/src/features/courses/modules/admin/add-module-item-drawer.tsx
  frontend/src/features/courses/modules/content/module-content-view.tsx
  frontend/src/features/courses/modules/module-panel.tsx
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
  frontend/src/pages/admin/lms/$lmsCode/modules/index.tsx
  frontend/src/pages/shared/lms/$lmsCode/modules/$itemId/index.tsx
  frontend/src/utils/formatters.ts
  frontend/src/utils/helpers.tsx
Labels: enhancement, fix / hotfix

#148 [CAP-232] HOTFIX: (FE) Updating Module Content Causes an Error
  frontend/src/features/courses/cms/cms.tsx
Labels: fix / hotfix
