Repository YKZSolutions/MMDC-Student-Portal, pull requests merged in 2025-08, with the labels that each got.

#13 FEAT: (FE) Initialize User Management Page and UI Enhancements [CAP-10]
  backend/src/generated/nestjs-dto/user.entity.ts
  frontend/src/integrations/mantine/mantine-theme.ts
  frontend/src/pages/admin/users.admin.tsx
  frontend/src/pages/shared/topbar.tsx
  frontend/src/routes/(protected)/dashboard.tsx
  frontend/src/routes/(protected)/route.tsx
  frontend/src/routes/(protected)/users.tsx
Labels: enhancement

#17 FEAT: FE Implement Password Reset Flow and Updated Associated Pages and Routing [CAP-]
  .gitattributes
  backend/src/modules/auth/auth.service.ts
  frontend/src/features/auth/auth.hook.ts
  frontend/src/features/validation/custom-validaitons.ts
  frontend/src/pages/shared/login-page.tsx
  frontend/src/pages/shared/reset-password-page.tsx
  frontend/src/pages/shared/update-password-page.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/(auth)/reset-password.tsx
  frontend/src/routes/(auth)/update-password.tsx
  supabase/config.toml
  supabase/package.json
Labels: enhancement

#19 FEAT: (FE) Integrate Search and Filtering on User Management Page [CAP-18]
  backend/src/modules/users/dto/filter-user.dto.ts
  backend/src/modules/users/users.controller.ts
  backend/src/modules/users/users.service.ts
  frontend/package.json
  frontend/src/features/user-management/constants.tsx
  frontend/src/features/user-management/types.ts
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/@tanstack/react-query.gen.ts
  frontend/src/integrations/api/client/sdk.gen.ts
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
  frontend/src/main.tsx
  frontend/src/pages/admin/users.admin.suspense.tsx
  frontend/src/pages/admin/users.admin.tsx
  frontend/src/routes/(protected)/users.tsx
  frontend/src/utils/formatters.ts
  pnpm-lock.yaml
Labels: enhancement

#20 FEAT: BE Add user invitations [cap-7]
  backend/src/config/env.schema.ts
  backend/src/modules/auth/auth.service.ts
  backend/src/modules/users/dto/invite-user.dto.ts
  backend/src/modules/users/users.controller.ts
  backend/src/modules/users/users.service.ts
  frontend/src/features/auth/auth.hook.ts
  supabase/config.toml
  supabase/templates/invite.html
Labels: enhancement

#22 FEAT: (BE) Create & Update User Refactor [CAP-33]
  backend/prisma/migrations/20250805204431_updated_at_default_value/migration.sql
  backend/prisma/schema.prisma
  backend/src/generated/nestjs-dto/create-user.dto.ts
  backend/src/generated/nestjs-dto/update-user.dto.ts
  backend/src/modules/auth/auth.service.ts
  backend/src/modules/users/dto/create-user.dto.ts
  backend/src/modules/users/dto/invite-user.dto.ts
  backend/src/modules/users/dto/update-user-details.dto.ts
  backend/src/modules/users/dto/user-credentials.dto.ts
  backend/src/modules/users/users.controller.ts
  backend/src/modules/users/users.service.ts
Labels: enhancement

#23 FEAT: (BE) implement authenticated user details retrieval via Supabase auth UID [CAP-25]
  backend/prisma/schema.prisma
  backend/src/common/decorators/auth-user.decorator.ts
  backend/src/generated/nestjs-dto/connect-userAccount.dto.ts
  backend/src/modules/users/dto/user-details.dto.ts
  backend/src/modules/users/users.controller.ts
  backend/src/modules/users/users.service.ts
Labels: enhancement

#24 FEAT: (FE) Billing Page Layout [CAP-26]
  frontend/src/features/navigation/navLinks.tsx
  frontend/src/features/user-management/types.ts
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/@tanstack/react-query.gen.ts
  frontend/src/integrations/api/client/sdk.gen.ts
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
  frontend/src/pages/admin/users.admin.tsx
  frontend/src/pages/shared/billing/$billingId.tsx
  frontend/src/pages/shared/billing/index.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/(protected)/billing.tsx
  frontend/src/routes/(protected)/billing/$billingId.tsx
  frontend/src/routes/(protected)/billing/index.tsx
Labels: enhancement

#27 FEAT: (FE) Implement Profile Page [CAP-24]
  backend/src/modules/users/users.controller.ts
  frontend/openapi-ts-error-1754721465890.log
  frontend/src/components/ErrorComponent.tsx
  frontend/src/components/Loader.tsx
  frontend/src/features/navigation/navLinks.tsx
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/@tanstack/react-query.gen.ts
  frontend/src/integrations/api/client/sdk.gen.ts
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
  frontend/src/pages/shared/profile.tsx
  frontend/src/routes/(protected)/profile.tsx
Labels: enhancement

#31 [CAP-27] FEAT: PayMongo Integration / Setup
  backend/package.json
  backend/src/app.module.ts
  backend/src/config/env.schema.ts
  backend/src/modules/billing/billing.controller.spec.ts
  backend/src/modules/billing/billing.controller.ts
  backend/src/modules/billing/billing.module.ts
  backend/src/modules/billing/billing.service.ts
  backend/src/modules/billing/dto/create-billing.dto.ts
  backend/src/modules/billing/dto/payment-intent.dto.ts
  backend/src/modules/billing/dto/update-billing.dto.ts
  backend/src/modules/users/users.service.ts
  frontend/package.json
  frontend/src/features/billing/types.ts
  frontend/src/features/modals/ewallet-modal.tsx
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/@tanstack/react-query.gen.ts
  frontend/src/integrations/api/client/sdk.gen.ts
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
  frontend/src/integrations/mantine/mantine-modals.ts
  frontend/src/main.tsx
  frontend/src/pages/admin/users/users.admin.tsx
  frontend/src/pages/shared/billing/$billingId.tsx
  pnpm-lock.yaml
Labels: enhancement

#34 [CAP-52] FEAT: Setup n8n
  .gitignore
  n8n/compose.yml
  n8n/tailscale/serve.json
  n8n/traefik/config/static.yml
Labels: enhancement

#46 [CAP-76] FIX: FE & BE Fix Payment Intent Type Error on the Frontend
  backend/src/modules/payments/dto/create-payment.dto.ts
  backend/src/modules/payments/dto/initiate-payment.dto.ts
  backend/src/modules/payments/payments.controller.ts
  backend/src/modules/payments/payments.service.ts
  frontend/src/features/modals/ewallet-modal.tsx
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/@tanstack/react-query.gen.ts
  frontend/src/integrations/api/client/sdk.gen.ts
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
Labels: fix / hotfix

#45 [CAP-53] FEAT: FE Chatbot Response Implementation
  backend/src/lib/gemini/gemini-session.store.ts
  backend/src/lib/gemini/gemini.service.ts
  backend/src/modules/auth/auth.service.ts
  backend/src/modules/chatbot/chatbot.controller.ts
  backend/src/modules/chatbot/chatbot.module.ts
  backend/src/modules/chatbot/chatbot.service.ts
  backend/src/modules/chatbot/dto/chatbot-response.dto.ts
  backend/src/modules/chatbot/dto/prompt.dto.ts
  backend/src/modules/chatbot/dto/user-context.dto.ts
  backend/src/modules/users/users.service.ts
  frontend/src/features/chatbot/chat-header.tsx
  frontend/src/features/chatbot/chat-input.tsx
  frontend/src/features/chatbot/chat-messages.tsx
  frontend/src/features/chatbot/drop-zone-indicator.tsx
  frontend/src/features/chatbot/types.ts
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/@tanstack/react-query.gen.ts
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
  frontend/src/pages/shared/layout/chatbot.tsx
Labels: enhancement

#49 [CAP-61 & 69] REFACTOR: (FE) Implement PayMongo Redirect Landing Page and Enhance Billing Details UI
  frontend/src/features/modals/ewallet-modal.tsx
  frontend/src/pages/shared/billing/$billingId.tsx
  frontend/src/pages/shared/billing/redirect.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/(protected)/billing/redirect.tsx
Labels: enhancement

#50 Change: Add unique constraint to `courseCode` in `Course` model
  backend/prisma/migrations/20250816111219_add_unique_constraint_to_course_course_code/migration.sql
  backend/prisma/schema.prisma
  backend/src/generated/nestjs-dto/connect-course.dto.ts
Labels: enhancement

#48 [CAP-74] FEAT: (BE) Logging & Error Handling System via Custom Decorators
  backend/src/common/decorators/auth-user.decorator.ts
  backend/src/common/decorators/log.decorator.ts
  backend/src/common/decorators/prisma-error.decorator.ts
  backend/src/common/interfaces/auth.user-metadata.ts
  backend/src/modules/test/dto/test-body.dto.ts
  backend/src/modules/test/dto/test-nested.dto.ts
  backend/src/modules/test/test.controller.ts
  backend/src/modules/test/test.module.ts
  backend/src/modules/test/test.service.ts
Labels: enhancement

#53 [CAP-50 & 85] FEAT: (BE/FE} Enhanced Chatbot Functionality with Vector Search and Markdown Rendering
  backend/src/config/env.schema.ts
  backend/src/lib/gemini/function-declarations.ts
  backend/src/lib/gemini/gemini.service.ts
  backend/src/lib/n8n/n8n.service.ts
  backend/src/modules/chatbot/chatbot.module.ts
  backend/src/modules/chatbot/chatbot.service.ts
  frontend/package.json
  frontend/src/pages/shared/layout/chatbot.tsx
  pnpm-lock.yaml
Labels: enhancement

#60 [CAP-92] FIX: BE Add New Prisma Commands for the GHA Tests
  .github/workflows/pr-type-check.yml
  backend/package.json
  package.json
Labels: fix / hotfix

#73 [CAP-90] FEAT: FE (Implement Courses Initial Layout)
  frontend/package.json
  frontend/src/components/btn-w-modal.tsx
  frontend/src/components/card-w-modal.tsx
  frontend/src/components/form-row.tsx
  frontend/src/components/role-based-action-button.tsx
  frontend/src/components/search-component.tsx
  frontend/src/components/submit-button.tsx
  frontend/src/components/types.ts
  frontend/src/features/courses/assignments/assignment-card.tsx
  frontend/src/features/courses/assignments/assignment-panel.tsx
  frontend/src/features/courses/assignments/types.ts
  frontend/src/features/courses/course-actions-selector.tsx
  frontend/src/features/courses/course-creation-card.tsx
  frontend/src/features/courses/course-editor/content-details-editor.tsx
  frontend/src/features/courses/course-editor/course-creation-process-modal.tsx
  frontend/src/features/courses/course-editor/course-tree.tsx
  frontend/src/features/courses/course-editor/useCurrentMeeting.ts
  frontend/src/features/courses/course-editor/useSubmissionDetails.ts
  frontend/src/features/courses/course-editor/useTreeConnectors.ts
  frontend/src/features/courses/course-navbar.tsx
  frontend/src/features/courses/course-quick-actions.tsx
  frontend/src/features/courses/course-task-summary.tsx
  frontend/src/features/courses/grades/types.ts
  frontend/src/features/courses/group/types.ts
  frontend/src/features/courses/module-creation-card.tsx
  frontend/src/features/courses/types.ts
  frontend/src/features/navigation/navLinks.tsx
  frontend/src/integrations/mantine/mantine-theme.ts
  frontend/src/pages/shared/courses/$courseId/assignments/course-assignments.tsx
  frontend/src/pages/shared/courses/$courseId/course-overview.tsx
  frontend/src/pages/shared/courses/$courseId/grades/course-grades.tsx
  frontend/src/pages/shared/courses/$courseId/modules/course-modules.tsx
  frontend/src/pages/shared/courses/course-dashboard.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/(protected)/courses/$courseCode.tsx
  frontend/src/routes/(protected)/courses/$courseCode/assignments/index.tsx
  frontend/src/routes/(protected)/courses/$courseCode/grades/index.tsx
  frontend/src/routes/(protected)/courses/$courseCode/index.tsx
  frontend/src/routes/(protected)/courses/$courseCode/modules/index.tsx
  frontend/src/routes/(protected)/courses/index.tsx
  frontend/src/routes/(protected)/route.tsx
  frontend/src/styles.css
  frontend/src/utils/formatters.ts
  frontend/src/utils/handlers.ts
  frontend/src/utils/helpers.ts
  pnpm-lock.yaml
Labels: enhancement

#75 [CAP-104] Refactor: (BE & FE) Bill FindOne Service Return Data
  backend/src/modules/billing/billing.service.ts
  backend/src/modules/billing/dto/detailed-bill.dto.ts
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/@tanstack/react-query.gen.ts
  frontend/src/integrations/api/client/sdk.gen.ts
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
  frontend/src/pages/shared/billing/$billingId.tsx
Labels: enhancement

#76 [CAP-114] FIX: (BE) Role Filtering for UserController FindAll
  backend/src/modules/users/dto/filter-user.dto.ts
Labels: fix / hotfix

#77 [CAP-117] CONF: (BE) Add Name for CourseOffering model
  backend/prisma/schema.prisma
  backend/src/generated/nestjs-dto/connect-courseSection.dto.ts
  backend/src/generated/nestjs-dto/courseSection.dto.ts
  backend/src/generated/nestjs-dto/courseSection.entity.ts
  backend/src/generated/nestjs-dto/create-courseSection.dto.ts
  backend/src/generated/nestjs-dto/update-courseSection.dto.ts
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
Labels: enhancement

#80 [CAP-123] CONF: (BE) Make mentorId optional for creating a CourseSection
  backend/prisma/schema.prisma
  backend/src/generated/nestjs-dto/courseSection.entity.ts
  backend/src/modules/enrollment/dto/create-courseSection.dto.ts
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
Labels: enhancement

#81 [CAP-97] FEAT: (FE) Refactor Course Creation Workflow and UI.
  frontend/src/components/btn-w-modal.tsx
  frontend/src/components/card-w-modal.tsx
  frontend/src/components/form-row.tsx
  frontend/src/components/icon-selector.tsx
  frontend/src/components/role-based-action-button.tsx
  frontend/src/components/search-component.tsx
  frontend/src/components/submit-button.tsx
  frontend/src/components/suspended-table-rows.tsx
  frontend/src/components/types.ts
  frontend/src/features/billing/async-employee-combobox.tsx
  frontend/src/features/courses/assignments/assignment-card.tsx
  frontend/src/features/courses/assignments/assignment-panel.tsx
  frontend/src/features/courses/assignments/types.ts
  frontend/src/features/courses/course-actions-modal.tsx
  frontend/src/features/courses/course-creation-card.tsx
  frontend/src/features/courses/course-creation-modal.tsx
  frontend/src/features/courses/course-editor/content-details-editor.tsx
  frontend/src/features/courses/course-editor/course-creation-process-modal.tsx
  frontend/src/features/courses/course-editor/course-tree.tsx
  frontend/src/features/courses/course-editor/useSubmissionDetails.ts
  frontend/src/features/courses/course-editor/useTreeConnectors.ts
  frontend/src/features/courses/course-main-layout.tsx
  frontend/src/features/courses/course-navbar.tsx
  frontend/src/features/courses/course-task-summary.tsx
  frontend/src/features/courses/dashboard/course-dashboard-quick-actions.tsx
  frontend/src/features/courses/grades/course-grades-table.tsx
  frontend/src/features/courses/grades/types.ts
  frontend/src/features/courses/group/types.ts
  frontend/src/features/courses/module-creation-card.tsx
  frontend/src/features/courses/modules/module-creation-panel.tsx
  frontend/src/features/courses/modules/module-creation-process-modal.tsx
  frontend/src/features/courses/modules/module-list-panel.tsx
  frontend/src/features/courses/modules/module-review-step.tsx
  frontend/src/features/courses/modules/types.ts
  frontend/src/features/courses/types.ts
  frontend/src/features/courses/useCurrentMeeting.ts
  frontend/src/features/courses/useSubmissionDetails.ts
  frontend/src/features/courses/useTreeConnectors.ts
  frontend/src/features/user-management/constants.tsx
  frontend/src/features/user-management/types.ts
  frontend/src/features/validation/custom-validaitons.ts
  frontend/src/pages/admin/enrollment/index.tsx
  frontend/src/pages/shared/courses/$courseId/assignments/course-assignments.tsx
  frontend/src/pages/shared/courses/$courseId/course-overview.tsx
  frontend/src/pages/shared/courses/$courseId/grades/course-grades.tsx
  frontend/src/pages/shared/courses/$courseId/modules/course-modules.tsx
  frontend/src/pages/shared/courses/course-dashboard.tsx
  frontend/src/pages/shared/layout/chatbot.tsx
  frontend/src/pages/shared/layout/topbar.tsx
  frontend/src/routes/(protected)/courses/$courseCode.tsx
  frontend/src/routes/(protected)/courses/$courseCode/assignments/index.tsx
  frontend/src/routes/(protected)/courses/$courseCode/grades/index.tsx
  frontend/src/routes/(protected)/courses/$courseCode/index.tsx
  frontend/src/routes/(protected)/courses/$courseCode/modules/index.tsx
  frontend/src/routes/(protected)/courses/index.tsx
  frontend/src/routes/(protected)/route.tsx
  frontend/src/utils/formatters.ts
  frontend/src/utils/handlers.ts
  frontend/src/utils/helpers.ts
Labels: enhancement, fix / hotfix

#82 [CAP-51] REFACTOR : (FE) Implement drag-to-close functionality and hide FAB by default
  frontend/src/pages/shared/layout/chatbot.tsx
  frontend/src/routes/(protected)/route.tsx
  frontend/src/styles.css
Labels: enhancement, fix / hotfix

#85 [CAP-51] FIX: (FE) Chatbot Window Constraint and Positioning
  frontend/src/pages/shared/layout/chatbot.tsx
Labels: fix / hotfix

#79 [CAP-103] FEAT: (BE) Enrollment module enhancements & student enrollment flow
  backend/src/common/guards/role.guard.ts
  backend/src/modules/enrollment/courseEnrollment.controller.ts
  backend/src/modules/enrollment/courseEnrollment.service.ts
  backend/src/modules/enrollment/courseOffering.controller.ts
  backend/src/modules/enrollment/courseOffering.service.ts
  backend/src/modules/enrollment/courseSection.controller.ts
  backend/src/modules/enrollment/courseSection.service.ts
  backend/src/modules/enrollment/dto/studentIdentifier.dto.ts
  backend/src/modules/enrollment/enrollment.controller.ts
  backend/src/modules/enrollment/enrollment.module.ts
  backend/src/modules/enrollment/enrollment.service.ts
  frontend/src/integrations/api/api-spec.json
  frontend/src/integrations/api/client/@tanstack/react-query.gen.ts
  frontend/src/integrations/api/client/sdk.gen.ts
  frontend/src/integrations/api/client/types.gen.ts
  frontend/src/integrations/api/client/zod.gen.ts
Labels: enhancement, help wanted
